server:
  port: 11000
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #\u81EA\u589E\u4E3B\u952E\u8BBE\u7F6E
  global-config:
    db-config:
      id-type: auto